export default function(Vue) {
  const i18n = Vue.$t('RetentionRate')
  return [
    // {
    //   type: 'selection',
    //   width: 30,
    //   title: '',
    //   fixed: 'left',
    //   align: 'center'
    // },
    {
      title: i18n.RetentionRate58,
      align: 'center',
      minWidth: 100,
      key: 'agent_name',
      // sortable: 'custom',
    },
    {
      title: i18n.RetentionRate0,
      align: 'center',
      minWidth: 100,
      key: 'date',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate4,
      align: 'center',
      minWidth: 100,
      key: 'first_deposit_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate5,
      align: 'center',
      minWidth: 100,
      key: 'first_deposit_amount',
      sortable: 'custom',
    },
    {
      title: `${i18n.RetentionRate65_v_1_2_4_8}`,//老充人数
      align: 'center',
      minWidth: 100,
      key: 'old_user_cnt',
      sortable: 'custom',
    },
    {
      title: `${i18n.RetentionRate66_v_1_2_4_8}`,//老充金额
      align: 'center',
      minWidth: 100,
      key: 'old_user_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate6,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate7,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate8,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_rr',
      render: (h, { row }) => <span>{`${row.tomorrow_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate9,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate10,
      align: 'center',
      minWidth: 100,
      key: 'three_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate11,
      align: 'center',
      minWidth: 100,
      key: 'three_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate12,
      align: 'center',
      minWidth: 100,
      key: 'three_rr',
      render: (h, { row }) => <span>{`${row.three_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate13,
      align: 'center',
      minWidth: 100,
      key: 'three_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate14,
      align: 'center',
      minWidth: 100,
      key: 'five_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate15,
      align: 'center',
      minWidth: 100,
      key: 'five_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate16,
      align: 'center',
      minWidth: 100,
      key: 'five_rr',
      render: (h, { row }) => <span>{`${row.five_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate17,
      align: 'center',
      minWidth: 100,
      key: 'five_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate18,
      align: 'center',
      minWidth: 100,
      key: 'seven_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate19,
      align: 'center',
      minWidth: 100,
      key: 'seven_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate20,
      align: 'center',
      minWidth: 100,
      key: 'seven_rr',
      render: (h, { row }) => <span>{`${row.seven_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate21,
      align: 'center',
      minWidth: 100,
      key: 'seven_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate22,
      align: 'center',
      minWidth: 100,
      key: 'fif_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate23,
      align: 'center',
      minWidth: 100,
      key: 'fif_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate24,
      align: 'center',
      minWidth: 100,
      key: 'fif_rr',
      render: (h, { row }) => <span>{`${row.fif_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate25,
      align: 'center',
      minWidth: 100,
      key: 'fif_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate26,
      align: 'center',
      minWidth: 100,
      key: 'thirty_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate27,
      align: 'center',
      minWidth: 100,
      key: 'thirty_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate28,
      align: 'center',
      minWidth: 100,
      key: 'thirty_rr',
      render: (h, { row }) => <span>{`${row.thirty_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate29,
      align: 'center',
      minWidth: 100,
      key: 'thirty_avg',
      sortable: 'custom',
    }
  ]
}
