export default function(Vue) {
  const i18n = Vue.$t('RetentionRate')
  return [
    // {
    //   type: 'selection',
    //   width: 30,
    //   title: '',
    //   fixed: 'left',
    //   align: 'center'
    // },
    {
      title: i18n.RetentionRate58,
      align: 'center',
      minWidth: 100,
      key: 'agent_name',
      // sortable: 'custom',
    },
    {
      title: i18n.RetentionRate0,
      align: 'center',
      minWidth: 100,
      key: 'date',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate30,
      align: 'center',
      minWidth: 100,
      key: 'active_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate31,
      align: 'center',
      minWidth: 100,
      key: 'active_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate33,
      align: 'center',
      minWidth: 100,
      key: 'active_amount_avg',
      sortable: 'custom',
    },
    // {
    //   title: `留存率`,
    //   align: 'center',
    //   minWidth: 100,
    //   key: 'active_rr',
    //   sortable: 'custom',
    // },
    {
      title: i18n.RetentionRate34,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate35,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate36,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate37,
      align: 'center',
      minWidth: 100,
      key: 'tomorrow_rr',
      render: (h, { row }) => <span>{`${row.tomorrow_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate38,
      align: 'center',
      minWidth: 100,
      key: 'three_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate39,
      align: 'center',
      minWidth: 100,
      key: 'three_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate40,
      align: 'center',
      minWidth: 100,
      key: 'three_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate41,
      align: 'center',
      minWidth: 100,
      key: 'three_rr',
      render: (h, { row }) => <span>{`${row.three_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate42,
      align: 'center',
      minWidth: 100,
      key: 'five_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate43,
      align: 'center',
      minWidth: 100,
      key: 'five_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate44,
      align: 'center',
      minWidth: 100,
      key: 'five_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate45,
      align: 'center',
      minWidth: 100,
      key: 'five_rr',
      render: (h, { row }) => <span>{`${row.five_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate46,
      align: 'center',
      minWidth: 100,
      key: 'seven_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate47,
      align: 'center',
      minWidth: 100,
      key: 'seven_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate48,
      align: 'center',
      minWidth: 100,
      key: 'seven_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate49,
      align: 'center',
      minWidth: 100,
      key: 'seven_rr',
      render: (h, { row }) => <span>{`${row.seven_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate50,
      align: 'center',
      minWidth: 100,
      key: 'fif_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate51,
      align: 'center',
      minWidth: 100,
      key: 'fif_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate52,
      align: 'center',
      minWidth: 100,
      key: 'fif_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate53,
      align: 'center',
      minWidth: 100,
      key: 'fif_rr',
      render: (h, { row }) => <span>{`${row.fif_rr}%`}</span>,
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate54,
      align: 'center',
      minWidth: 100,
      key: 'thirty_num',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate55,
      align: 'center',
      minWidth: 100,
      key: 'thirty_amount',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate56,
      align: 'center',
      minWidth: 100,
      key: 'thirty_avg',
      sortable: 'custom',
    },
    {
      title: i18n.RetentionRate57,
      align: 'center',
      minWidth: 100,
      key: 'thirty_rr',
      render: (h, { row }) => <span>{`${row.thirty_rr}%`}</span>,
      sortable: 'custom',
    }
  ]
}
